import { Role } from './entities/role.entity';
import { SystemRoleSlug } from './enums/role.enum';

export const SYSTEM_ROLES: Partial<Role>[] = [
	{ name: 'проректор', slug: SystemRoleSlug.PROREKTOR},
	{ name: 'декан', slug: SystemRoleSlug.DEKAN },
	{ name: 'директор ННІ ЗУП', slug: SystemRoleSlug.DYREKTOR_NNI_ZUP },
	{ name: 'заступник декана', slug: SystemRoleSlug.ZASTUPNYK_DEKANA },
	{ name: 'завідувач кафедри', slug: SystemRoleSlug.ZAVIDUVACH_KAFEDRY },
	{ name: 'куратор академічної групи', slug: SystemRoleSlug.KURATOR_AKADEMICHNOYI_HRUPY },
	{ name: 'гарант ОПП', slug: SystemRoleSlug.HARANT_OPP },
	{ name: 'керівник НДІ', slug: SystemRoleSlug.KERIVNYK_NDI },
	{ name: 'викладач кафедри', slug: SystemRoleSlug.VYKLADACH_KAFEDRY },
	{ name: 'член вченої ради університету', slug: SystemRoleSlug.CHLEN_VCHENOYI_RADY_UNIVERSYTETU },
	{ name: 'член вченої ради факультету', slug: SystemRoleSlug.CHLEN_VCHENOYI_RADY_FAKULTETU },
	{ name: 'секретар вченої ради факультету', slug: SystemRoleSlug.SEKRETAR_VCHENOYI_RADY_FAKULTETU },
	{ name: 'член науково-методичної ради', slug: SystemRoleSlug.CHLEN_NAUKOVO_METODYCHNOYI_RADY },
	{ name: 'начальник відділу', slug: SystemRoleSlug.NACHALNYK_VIDDILU },
	{ name: 'допоміжний персонал', slug: SystemRoleSlug.DOPOMIZHNYY_PERSONAL },
	{ name: 'технічний секретар приймальної комісії', slug: SystemRoleSlug.TEKHNICHNYY_SEKRETAR_PRYYMALNOYI_KOMISIYI },
	{ name: 'секретар деканата', slug: SystemRoleSlug.SEKRETAR_DEKANATA },
	{ name: 'відповідальний за науку по кафедрі', slug: SystemRoleSlug.VIDPOVIDALNYY_ZA_NAUKU_PO_KAFEDRI },
	{ name: 'координатор з інтернаціоналізації по кафедрі', slug: SystemRoleSlug.KOORDYNATOR_Z_INTERNATSIONALIZATSIYI_PO_KAFEDRI },
	{ name: 'відповідальний за наповнення сайту', slug: SystemRoleSlug.VIDPOVIDALNYY_ZA_NAPOVNENNYA_SAYTU },
	{ name: 'куратор дуального навчання', slug: SystemRoleSlug.KURATOR_DUALNOHO_NAVCHANNYA },
	{ name: 'профорг кафедри', slug: SystemRoleSlug.PROFORH_KAFEDRY },
	{ name: 'профорг факультету', slug: SystemRoleSlug.PROFORH_FAKULTETU },
	{ name: 'відповідальний за практики на кафедрі', slug: SystemRoleSlug.VIDPOVIDALNYY_ZA_PRAKTYKY_NA_KAFEDRI },
	{ name: 'секретар засідання кафедри', slug: SystemRoleSlug.SEKRETAR_ZASIDANNYA_KAFEDRY },
	{ name: 'секретар засідання вченої ради факультету', slug: SystemRoleSlug.SEKRETAR_ZASIDANNYA_VCHENOYI_RADY_FAKULTETU },
	{ name: 'голова метод комісії факультету', slug: SystemRoleSlug.HOLOVA_METOD_KOMISIYI_FAKULTETU },
	{ name: 'голова метод комісії кафедри', slug: SystemRoleSlug.HOLOVA_METOD_KOMISIYI_KAFEDRY },
	{ name: 'студент', slug: SystemRoleSlug.STUDENT },
	{ name: 'староста', slug: SystemRoleSlug.STAROSTA },
	{ name: 'заступник старости', slug: SystemRoleSlug.ZASTUPNYK_STAROSTY },
	{ name: 'член органів студентського самоврядування', slug: SystemRoleSlug.CHLEN_ORHANIV_STUDENTSKOHO_SAMOVRYADUVANNYA },
	{ name: 'адміністратор', slug: SystemRoleSlug.ADMINISTRATOR },
]